### ISSUE TITLE
Trying to build on Rocks node running CentOS 7.6

### ISSUE THREAD

**Issue by munorc** [sdsc/mlnx-ofed-roll#3]
I am looking to build the mlnx_ofed roll on an updated Rocks install with CentOS 7.6 and teh current MLNX_OFED version 4.6-1.0.1.1 .   I had built this succesfully with CentOS 7.5 and MLNX_OFED 4.5

Seems to fail early on

# more build.log 
/opt/rocks/share/devel/src/roll/../../etc/rocks-version.mk:286: rocks-version-common.mk: No such file or directory
/opt/rocks/share/devel/src/roll/../../etc/python.mk:14: rocks-version-common.mk: No such file or directory
/opt/rocks/share/devel/src/roll/../../etc/Rules.mk:707: Rules-install.mk: No such file or directory
/opt/rocks/share/devel/src/roll/../../etc/Rules.mk:782: Rules-scripts.mk: No such file or directory
/opt/rocks/share/devel/src/roll/../../etc/Rules.mk:813: Rules-rcfiles.mk: No such file or directory
/opt/rocks/share/devel/src/roll/etc/Rolls.mk:280: Rules.mk: No such file or directory
/opt/rocks/share/devel/src/roll/etc/Rolls.mk:283: roll-profile.mk: No such file or directory
/opt/rocks/share/devel/src/roll/etc/Rolls.mk:286: Rules-repo-centos.mk: No such file or directory
Makefile:63: Rolls.mk: No such file or directory
cp /opt/rocks/share/devel/src/roll/etc/Rolls.mk Rolls.mk
cp /opt/rocks/share/devel/src/roll/etc/Rules-repo-centos.mk Rules-repo-centos.mk
cp /opt/rocks/share/devel/src/roll/etc/roll-profile.mk roll-profile.mk
cp /opt/rocks/share/devel/src/roll/../../etc/Rules.mk Rules.mk
cp /opt/rocks/share/devel/src/roll/../../etc/Rules-linux.mk Rules-linux.mk
cp /opt/rocks/share/devel/src/roll/../../etc/Rules-linux-centos.mk Rules-linux-centos.mk
cp /opt/rocks/share/devel/src/roll/../../etc/python.mk python.mk
cp /opt/rocks/share/devel/src/roll/../../etc/rocks-version-common.mk rocks-version-common.mk
cp /opt/rocks/share/devel/src/roll/../../etc/rocks-version.mk rocks-version.mk
master_new.
/opt/rocks/share/devel/src/roll/../../etc/Rules.mk:622: *** first argument to `word' function must be greater than 0.  Stop.

**Comment by hpcdevops** [comment]
Without more information (ie. roll source filesystem location and command(s) run) I am guessing a bit with this solution.

The error is coming from one of the _base_ Rocks roll make include files. This file is added to the repository source when you run `make` at the top level. Have a look at this file in the area where the error is reported. For example (my roll source is different but the concept is the same)...

```
[tcooper@manzanita-fe zfs-linux]$ cat -n Rules.mk | grep 622 -B10 -A6
   612
   613	# --------------------------------------------------------------------- #
   614	# Compute the package name based on the last two directory names
   615	# --------------------------------------------------------------------- #
   616
   617	PATH.CHILD	= $(notdir $(CURDIR))
   618	PATH.PARENTPATH	= $(dir $(CURDIR))
   619	PATH.PARENTLIST	= $(subst /, ,$(dir $(CURDIR)))
   620	PATH.PARENT	= $(word $(words $(PATH.PARENTLIST)), $(PATH.PARENTLIST))
   621	PATH.GRANDPARENTLIST = $(subst $(PATH.PARENT),,$(PATH.PARENTLIST))
   622	PATH.GRANDPARENT     = $(word $(words $(PATH.GRANDPARENTLIST)), \
   623		$(PATH.GRANDPARENTLIST))
   624
   625	ifeq ($(NAME),)
   626	NAME		= $(PATH.PARENT)-$(PATH.CHILD)
   627	endif
   628
```

This should give you the clue that Rocks is trying to determine a package name from the location of your roll source in the filesystem.

Rocks roll builds are sensitive to where the roll source is located. I recommend you clone the roll source (or move your current source) to a directory **AT LEAST** two or three levels down in the filesystem hierarchy on your build server.

I typically use `/export/rocks/src/roll` and never see this particular issue in my builds.

**Comment by munorc** [comment]
I was able to build it with 

make roll

instead of 

make default
