### ISSUE TITLE
mlnx-ofed roll will not build on Centos 7.6.1810 with MLNX_OFED 4.7

### ISSUE THREAD

**Issue by munorc** [sdsc/mlnx-ofed-roll#5]
I have built the mlnx-ofed roll under CentOS 7.4, 7.5 and 7.6 with many variants of MLNX_OFED, including versions 4.3, 4.5 and 4.6.   Mellanox recently released  version 4.7 1.0.0.1. Following the same procedures, I can build the roll, and I do not see any apparent errors.  However, there are no relevant RPMS packaged in the roll. The only RPM's I see in it are:

mlnx-ofed-linux-4.7-1.0.0.1.x86_64.rpm
roll-mlnx-ofed-4.7-1.0.0.1-3.10.0-957.27.2.el7-kickstart-4.7-0..noarch.rpm
sdsc-mlnx-ofa_pythonresolve-1-0.x86_64.rpm

As a test, I just rebuilt the 4.6-1.0.1.1 version, on the same host,  and it completed successfully.

I can hand install the MLNX_OFED distribution on the machines with this OS config.

**Comment by munorc** [comment]
[build.log](https://github.com/sdsc/mlnx-ofed-roll/files/3681350/build.log)

Attached is the build.log for the attempted 4.7 build

**Comment by tcooper** [comment]
It appears Mellanox changed the hierarchy inside the RPMS sub-directory of the generated `MLNX_OFED_LINUX-4.7-1.0.0.1-rhel7.6-x86_64-ext.tgz` package.

While I haven't completed a full test of the install of RPMs from this version of MLNX_OFED_LINUX I can provide the following diff that should allow you to create a roll from the 4.7 1.0.0.1 version.

```
# git diff src/mlnx-ofed-linux/Makefile
diff --git a/src/mlnx-ofed-linux/Makefile b/src/mlnx-ofed-linux/Makefile
index 4194b59..33ed597 100644
--- a/src/mlnx-ofed-linux/Makefile
+++ b/src/mlnx-ofed-linux/Makefile
@@ -74,9 +74,9 @@ build: $(SRC_DIRS)
 install::
        mkdir -p $(ROOT)/$(PKGROOT)
        mkdir -p $(REDHAT.ROOT)/RPMS/{noarch,x86_64}
-       find $(SOURCE_DIR_EXT)/RPMS -mindepth 1 -maxdepth 1 -name "*.x86_64.rpm" -type f \
+       find $(SOURCE_DIR_EXT)/RPMS -mindepth 1 -name "*.x86_64.rpm" -type f \
          -exec cp -av '{}' ../../RPMS/x86_64/ \;
-       find $(SOURCE_DIR_EXT)/RPMS -mindepth 1 -maxdepth 1 -name "*.noarch.rpm" -type f \
+       find $(SOURCE_DIR_EXT)/RPMS -mindepth 1 -name "*.noarch.rpm" -type f \
          -exec cp -av '{}' ../../RPMS/noarch/ \;
        (       \
                cd $(ROOT)/$(PKGROOT); \
```

The roll I generated from source with this change contained most of the expected RPMS...

```
# ls -l mlnx-ofed-4.7-1.0.0.1.3.10.0-957.12.2.el7-7.0-26.g86f4899.x86_64.disk1.iso
-rw-r--r-- 1 root wheel 497946624 Oct  2 13:16 mlnx-ofed-4.7-1.0.0.1.3.10.0-957.12.2.el7-7.0-26.g86f4899.x86_64.disk1.iso

# isoinfo -R -f -i mlnx-ofed-4.7-1.0.0.1.3.10.0-957.12.2.el7-7.0-26.g86f4899.x86_64.disk1.iso | grep -E "\.rpm$" | wc -l
124
```

If/when we migrate one of our systems to this version of MLNX_OFED_LINUX I'll have a chance to fully test the install of these RPMs during node kickstart.
