### ISSUE TITLE
MLNX_OFED 4.7 issues

### ISSUE THREAD

**Issue by munorc** [sdsc/mlnx-ofed-roll#6]
The patch provided regarding the previous issue where no RPMS were packaged seems to have taken care of that issue. 

I followed the procedures in the CONFLICTS document. That took care of installation of version 4.6 under CentOS 7.6.1810.  With this release, there are additional RPM installation issues. 

Attached are the logs from the failed installation on a compute node. 

[packaging.log](https://github.com/sdsc/mlnx-ofed-roll/files/3687177/packaging.log)
[program.log](https://github.com/sdsc/mlnx-ofed-roll/files/3687178/program.log)
[syslog.log](https://github.com/sdsc/mlnx-ofed-roll/files/3687185/syslog.log)

**Comment by tcooper** [comment]
As per the statement at the end of the `CONFLICTS.md` file...

> As the selection of distribution, updates mechanism and MLNX_OFED_LINUX stack supported on a particular system is unique this note will be the only effort to describe and resolved this issue within this roll source.

Until we've had an opportunity to install/test/resolve issues in our own systems you will need to work through this yourself following the background in `CONFLICTS.md`.

By all means, if you are able to resolve you are welcome to provide the solution here and/or provide a pull request to update the documentation in this roll.
