### ISSUE TITLE
rebuilding roll with MLNX OFED 4.7 on CentOS 7 produces roll with wrong rpms

### ISSUE THREAD

**Issue by bernstei** [sdsc/mlnx-ofed-roll#7]
I tried to update to CentOS 7.7, with kernel 3.10.0-1062.1.2.el7.x86_64, which necessitated MLNX_OFED_LINUX-4.7-1.0.0.1-rhel7.7-x86_64.tgz.  I then tried to rebuild the roll according to the instructions in the README (copy MLNX_OFED_LINUX*tgz to src/mlnx-ofed-linux, edit version.mk and .mlnx in that directory, update the binary hashes, and update version.mk in the top directory), which worked in the past (with MLNX OFED 4.6, for example).  However, this time it produced a roll without the proper rpms.  Instead, it produces 3 weird rpms:
   mlnx-ofed-linux-4.7-1.0.0.1.x86_64.rpm
   roll-mlnx-ofed-4.7-1.0.0.1-3.10.0-1062.1.2.el7-kickstart-7.0-27.g7dbf8e7.noarch.rpm
   sdsc-mlnx-ofa_pythonresolve-1-0.x86_64.rpm
The kickstart then fails, I think because it can't find the rpms it's actually trying to install.

**Comment by bernstei** [comment]
I've done a bit more exploring, and I think I have a guess as to what's going wrong. src/mlnx-ofed-linux/Makefile looks for rpms using commands like "find MLNX_OFED_LINUX-4.7-1.0.0.1-rhel7.7-x86_64-ext/RPMS -mindepth 1 -maxdepth 1".  Unfortunately, that directory (mlnx-ofed-roll/BUILD/mlnx-ofed-linux-4.7/MLNX_OFED_LINUX-4.7-1.0.0.1-rhel7.7-x86_64-ext/RPMS) does not contain any rpms at depth 1.  Instead, there are subdirectories (COMMON, UPSTREAM_LIBS, and MLNX_LIBS) that contain the real rpms.  I'm not sure where the real change in the MLNX_OFED mlnxofedinstall process is, but for example the create_mlnx_ofed_installers.pl script has changed around line 811, something to do with directories of the same names.  

Perhaps someone who understands either/both installation processes might know what's going on?

**Comment by tcooper** [comment]
Look at issues #5 and #6

**Comment by bernstei** [comment]
Thanks.  Sorry I didn’t think to look in the closed issues.

								Noam
